<?php

namespace Material\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderformRepository extends EntityRepository
{
}
